services:
  app:
    build:
      target: dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
    command: npx nodemon -L index.js

  mock-server:
    build:
      target: dev

  db:
    ports:
      - "5433:5432"

  redis:
    ports:
      - "6380:6379"