services:
  app:
    image: ghcr.io/shadowofdeath25/hooks:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production

  worker:
    image: ghcr.io/shadowofdeath25/hooks:latest
    command: sh -c "node ./src/worker.js"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy